insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H001', 50, 'IMAX', 'CM001');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H002', 100, '3D', 'CM001');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H003', 150, 'ATMOS DOLBY', 'CM001');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H004', 200, 'STANDARD', 'CM001');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H005', 250, 'IMAX', 'CM001');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H006', 50, '3D', 'CM001');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H007', 100, 'ATMOS DOLBY', 'CM001');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H008', 150, 'STANDARD', 'CM001');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H009', 200, 'IMAX', 'CM001');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H010', 250, '3D', 'CM001');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H011', 50, 'IMAX', 'CM002');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H012', 100, '3D', 'CM002');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H013', 150, 'ATMOS DOLBY', 'CM002');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H014', 200, 'STANDARD', 'CM002');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H015', 250, 'IMAX', 'CM002');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H016', 50, '3D', 'CM002');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H017', 100, 'ATMOS DOLBY', 'CM002');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H018', 150, 'STANDARD', 'CM002');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H019', 200, 'IMAX', 'CM002');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H020', 250, '3D', 'CM002');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H021', 50, 'IMAX', 'CM003');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H022', 100, '3D', 'CM003');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H023', 150, 'ATMOS DOLBY', 'CM003');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H024', 200, 'STANDARD', 'CM003');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H025', 250, 'IMAX', 'CM003');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H026', 50, '3D', 'CM003');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H027', 100, 'ATMOS DOLBY', 'CM003');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H028', 150, 'STANDARD', 'CM003');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H029', 200, 'IMAX', 'CM003');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H030', 250, '3D', 'CM003');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H031', 50, 'IMAX', 'CM004');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H032', 100, '3D', 'CM004');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H033', 150, 'ATMOS DOLBY', 'CM004');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H034', 200, 'STANDARD', 'CM004');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H035', 250, 'IMAX', 'CM004');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H036', 50, '3D', 'CM004');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H037', 100, 'ATMOS DOLBY', 'CM004');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H038', 150, 'STANDARD', 'CM004');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H039', 200, 'IMAX', 'CM004');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H040', 250, '3D', 'CM004');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H041', 50, 'IMAX', 'CM005');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H042', 100, '3D', 'CM005');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H043', 150, 'ATMOS DOLBY', 'CM005');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H044', 200, 'STANDARD', 'CM005');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H045', 250, 'IMAX', 'CM005');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H046', 50, '3D', 'CM005');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H047', 100, 'ATMOS DOLBY', 'CM005');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H048', 150, 'STANDARD', 'CM005');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H049', 200, 'IMAX', 'CM005');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H050', 250, '3D', 'CM005');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H051', 50, 'IMAX', 'CM006');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H052', 100, '3D', 'CM006');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H053', 150, 'ATMOS DOLBY', 'CM006');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H054', 200, 'STANDARD', 'CM006');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H055', 250, 'IMAX', 'CM006');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H056', 50, '3D', 'CM006');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H057', 100, 'ATMOS DOLBY', 'CM006');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H058', 150, 'STANDARD', 'CM006');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H059', 200, 'IMAX', 'CM006');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H060', 250, '3D', 'CM006');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H061', 50, 'IMAX', 'CM007');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H062', 100, '3D', 'CM007');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H063', 150, 'ATMOS DOLBY', 'CM007');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H064', 200, 'STANDARD', 'CM007');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H065', 250, 'IMAX', 'CM007');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H066', 50, '3D', 'CM007');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H067', 100, 'ATMOS DOLBY', 'CM007');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H068', 150, 'STANDARD', 'CM007');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H069', 200, 'IMAX', 'CM007');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H070', 250, '3D', 'CM007');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H071', 50, 'IMAX', 'CM008');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H072', 100, '3D', 'CM008');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H073', 150, 'ATMOS DOLBY', 'CM008');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H074', 200, 'STANDARD', 'CM008');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H075', 250, 'IMAX', 'CM008');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H076', 50, '3D', 'CM008');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H077', 100, 'ATMOS DOLBY', 'CM008');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H078', 150, 'STANDARD', 'CM008');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H079', 200, 'IMAX', 'CM008');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H080', 250, '3D', 'CM008');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H081', 50, 'IMAX', 'CM009');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H082', 100, '3D', 'CM009');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H083', 150, 'ATMOS DOLBY', 'CM009');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H084', 200, 'STANDARD', 'CM009');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H085', 250, 'IMAX', 'CM009');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H086', 50, '3D', 'CM009');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H087', 100, 'ATMOS DOLBY', 'CM009');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H088', 150, 'STANDARD', 'CM009');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H089', 200, 'IMAX', 'CM009');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H090', 250, '3D', 'CM009');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H091', 50, 'IMAX', 'CM010');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H092', 100, '3D', 'CM010');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H093', 150, 'ATMOS DOLBY', 'CM010');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H094', 200, 'STANDARD', 'CM010');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H095', 250, 'IMAX', 'CM010');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H096', 50, '3D', 'CM010');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H097', 100, 'ATMOS DOLBY', 'CM010');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H098', 150, 'STANDARD', 'CM010');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H099', 200, 'IMAX', 'CM010');
insert into hall (hall_Id, hall_capacity, hall_info, cinema_Id) values ('H100', 250, '3D', 'CM010');