insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B001', 'M012', 'Get a free gift');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B002', 'M017', '10% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B003', 'M025', '20% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B004', 'M007', 'Free mini popcorn');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B005', 'M035', 'Buy 1, get 1 free ticket');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B006', 'M013', 'Buy 1, get 1 free ticket');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B007', 'M032', 'Buy 3, get 1 free seat');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B008', 'M010', 'Birthday free ticket');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B009', 'M026', 'Buy 1, get 1 free ticket');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B010', 'M034', 'Get a free gift');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B011', 'M007', 'Buy 1, get 50% off on second food');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B012', 'M011', 'Buy 1, get 50% off on second food');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B013', 'M004', '10% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B014', 'M008', '20% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B015', 'M020', 'Buy 3, get 1 free seat');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B016', 'M003', '10% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B017', 'M009', '20% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B018', 'M021', '10% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B019', 'M016', '10% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B020', 'M020', 'Free mini popcorn');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B021', 'M015', 'Buy 1, get 1 free food');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B022', 'M030', 'Buy 3, get 1 free seat');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B023', 'M001', 'Buy 1, get 1 free ticket');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B024', 'M027', 'Get a free drink');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B025', 'M035', 'Buy 1, get 50% off on second food');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B026', 'M012', 'Birthday free ticket');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B027', 'M017', 'Buy 3, get 1 free seat');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B028', 'M025', '10% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B029', 'M007', 'Get a free gift');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B030', 'M035', '10% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B031', 'M013', 'Buy 1, get 50% off on second food');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B032', 'M032', 'Buy 1, get 1 free ticket');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B033', 'M010', 'Buy 1, get 1 free ticket');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B034', 'M026', 'Free mini popcorn');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B035', 'M034', '10% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B036', 'M007', 'Birthday free ticket');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B037', 'M011', '20% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B038', 'M004', '20% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B039', 'M008', 'Birthday free ticket');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B040', 'M020', 'Buy 1, get 50% off on second food');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B041', 'M003', 'Get a free gift');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B042', 'M009', 'Birthday free ticket');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B043', 'M021', 'Buy 1, get 1 free food');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B044', 'M016', '20% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B045', 'M020', 'Buy 1, get 1 free ticket');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B046', 'M015', 'Get a free gift');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B047', 'M030', 'Buy 1, get 1 free food');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B048', 'M001', 'Free mini popcorn');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B049', 'M027', 'Get a free gift');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B050', 'M035', 'Get a free gift');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B051', 'M012', 'Buy 1, get 1 free ticket');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B052', 'M017', 'Buy 1, get 1 free ticket');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B053', 'M025', 'Get a free gift');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B054', 'M007', '20% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B055', 'M035', '20% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B056', 'M013', '10% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B057', 'M032', '10% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B058', 'M010', 'Get a free gift');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B059', 'M026', 'Buy 3, get 1 free seat');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B060', 'M034', 'Free mini popcorn');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B061', 'M007', '10% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B062', 'M011', ' Birthday free ticket');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B063', 'M004', 'Buy 3, get 1 free seat');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B064', 'M008', 'Buy 1, get 1 free ticket');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B065', 'M020', '10% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B066', 'M003', 'Birthday free ticket');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B067', 'M009', 'Buy 1, get 1 free food');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B068', 'M021', '20% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B069', 'M016', 'Buy 1, get 1 free ticket');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B070', 'M020', '20% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B071', 'M015', 'Free mini popcorn');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B072', 'M030', '10% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B073', 'M001', '20% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B074', 'M027', 'Free mini popcorn');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B075', 'M035', 'Birthday free ticket');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B076', 'M012', '10% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B077', 'M017', 'Free mini popcorn');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B078', 'M025', 'Buy 3, get 1 free seat');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B079', 'M007', 'Get a free drink');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B080', 'M035', 'Free mini popcorn');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B081', 'M013', 'Birthday free ticket');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B082', 'M032', 'Buy 1, get 1 free food');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B083', 'M010', '10% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B084', 'M026', '20% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B085', 'M034', ' 20% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B086', 'M007', 'Buy 1, get 1 free food');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B087', 'M011', '10% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B088', 'M004', 'Get a free gift');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B089', 'M008', 'Get a free gift');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B090', 'M020', 'Birthday free ticket');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B091', 'M003', '20% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B092', 'M009', 'Free mini popcorn');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B093', 'M021', 'Free mini popcorn');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B094', 'M016', 'Get a free gift');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B095', 'M020', 'Get a free drink');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B096', 'M015', '20% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B097', 'M030', 'Buy 1, get 1 free ticket');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B098', 'M001', '10% discount');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B099', 'M027', 'Buy 1, get 1 free ticket');
insert into Member_benefit (benefit_Id, member_Id, benefit_title) values ('B100', 'M035', ' Buy 1, get 1 free ticket');